name = "apollo-cloudflare-frontend"
compatibility_date = "2024-11-25"

assets = { directory = "./dist", not_found_handling = "single-page-application" }

[dev]
port = 3001
local_protocol = "http"

[env.prod]
routes = [
  { pattern = "yu-f87ct9a.dev", custom_domain = true }
]

[env.dev]
routes = [
  { pattern = "dev.yu-f87ct9a.dev", custom_domain = true }
]

[env.preview]
# Preview環境はrouteを設定しない（自動生成URLを使用）