name = "apollo-cloudflare-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# デフォルト環境変数
[vars]
ENVIRONMENT = "development"

# 開発サーバー設定
[dev]
port = 8787
local_protocol = "http"

# 開発環境設定
[env.dev]
name = "apollo-cloudflare-api-dev"
routes = [
  { pattern = "api.dev.yu-f87ct9a.dev", custom_domain = true }
]

[env.dev.vars]
ENVIRONMENT = "development"
GRAPHQL_INTROSPECTION = "true"
GRAPHQL_PLAYGROUND = "true"
CORS_ORIGIN = "https://dev.yu-f87ct9a.dev"
SUPABASE_URL = "https://tatdnqkazluqzfgecauc.supabase.co"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "apollo-cloudflare-db"
database_id = "c370ca69-c11d-4d00-9fd0-b7339850fd30"
migrations_dir = "migrations"

# 本番環境設定
[env.prod]
name = "apollo-cloudflare-api-prod"
routes = [
  { pattern = "api.yu-f87ct9a.dev", custom_domain = true }
]

[env.prod.vars]
ENVIRONMENT = "production"
GRAPHQL_INTROSPECTION = "false"
GRAPHQL_PLAYGROUND = "false"
CORS_ORIGIN = "https://yu-f87ct9a.dev"
SUPABASE_URL = "https://tatdnqkazluqzfgecauc.supabase.co"

[[env.prod.d1_databases]]
binding = "DB"
database_name = "apollo-cloudflare-db-prod"
database_id = "0e28d05c-20d4-49c4-a505-a0aba68a522d"
migrations_dir = "migrations"