name = "apollo-cloudflare-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# デフォルト環境変数
[vars]
ENVIRONMENT = "development"

# D1データベース設定（ローカル開発用）
[[d1_databases]]
binding = "DB"
database_name = "apollo-cloudflare-db"
database_id = "c370ca69-c11d-4d00-9fd0-b7339850fd30"
migrations_dir = "migrations"

[observability.logs]
enabled = true

# 開発サーバー設定
[dev]
port = 8787
local_protocol = "http"

# 開発環境設定
[env.dev]
name = "apollo-cloudflare-api-dev"
routes = [
  { pattern = "api.dev.yu-f87ct9a.dev", custom_domain = true }
]

[env.dev.vars]
ENVIRONMENT = "development"
GRAPHQL_INTROSPECTION = "true"
GRAPHQL_PLAYGROUND = "true"
CORS_ORIGIN = "https://dev.yu-f87ct9a.dev"
CLERK_PEM_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArmHdTw+M4xALbZn5roVl\nP8I9WYwkuHQMw/p4GoI9oIutoiNLd5+ICk/7gcgpeNbuLCZgjl1z+lbq9lJngUs7\nYAmBKgRS14fYvzXYxrgIXglqvqSpxMkcqA43sEhf+ABczUQXvpifief5dW8kcH1i\nYndMhmd+yO+0iHO15T2rx66uQ2wKSNDokpXFTmKEuPempCMIT/I4UO3FEfWwP8TT\nN4uBNfT9+bixtc4ITqxfHDiJGZjV3ExxMbUgs3FfUkqz5brPyk1MngzgDn+99+K9\n6l12PgjzzNpbeTn5G38Qw6gRWOqbQR5AaB/74q9d5xBTNY5S/5+Cf2tzTTZNrxz3\n3wIDAQAB\n-----END PUBLIC KEY-----"
CLERK_PUBLISHABLE_KEY="pk_test_bGlnaHQtYWtpdGEtNDcuY2xlcmsuYWNjb3VudHMuZGV2JA"

[[env.dev.d1_databases]]
binding = "DB"
database_name = "apollo-cloudflare-db"
database_id = "c370ca69-c11d-4d00-9fd0-b7339850fd30"
migrations_dir = "migrations"

# 本番環境設定
[env.prod]
name = "apollo-cloudflare-api-prod"
routes = [
  { pattern = "api.yu-f87ct9a.dev", custom_domain = true }
]

[env.prod.vars]
ENVIRONMENT = "production"
GRAPHQL_INTROSPECTION = "false"
GRAPHQL_PLAYGROUND = "false"
CORS_ORIGIN = "https://yu-f87ct9a.dev"

[[env.prod.d1_databases]]
binding = "DB"
database_name = "apollo-cloudflare-db-prod"
database_id = "0e28d05c-20d4-49c4-a505-a0aba68a522d"
migrations_dir = "migrations"