name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Generate and Build
        env:
          DATABASE_URL: "file:./dev.db"
        run: |
          # First generate backend schema
          pnpm --filter @apollo-cloudflare-react/backend generate
          # Then build all packages (frontend can now find schema.gql)
          pnpm build

      - name: Setup wrangler.jsonc files with account ID
        run: |
          # Setup account ID for all wrangler.jsonc files
          for package in backend frontend images-worker; do
            if [ -f "packages/$package/wrangler.jsonc" ]; then
              cd "packages/$package"
              # Insert account_id in JSON format after line 3
              sed -i '3a\  "account_id": "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}",' wrangler.jsonc
              echo "Updated wrangler.jsonc with account ID for $package"
              cd ../..
            fi
          done

      - name: Deploy all packages to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            pnpm deploy:prod
          else
            pnpm deploy:dev
          fi
